name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build website
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: npm i
      - name: test
        run: npm run test
